language: node_js

node_js:
    - "node"

cache:
    directories:
        - node_modules

before_install:
    - npm install
    - npm install codecov -g

script:
    - npm run build
    - npm test
    - npm run lint
    - npm run codeCoverage

after_success:
    - codecov
